<!--
%\VignetteEngine{knitr}
%\VignetteIndexEntry{Processing several measurement cycles}
-->

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(out.extra='style="display:block; margin: auto"'
    #, fig.align="center"
    , fig.width=4.3, fig.height=3.2, dev.args=list(pointsize=10)
    , message=FALSE
    )
knit_hooks$set(spar = function(before, options, envir) {
    if (before){
        par( las=1 )                   #also y axis labels horizontal
        par(mar=c(2.0,3.3,0,0)+0.3 )  #margins
        par(tck=0.02 )                          #axe-tick length inside plots             
        par(mgp=c(1.1,0.2,0) )  #positioning of axis title, axis labels, axis
     }
})
# genVigs("severalCycles")
```

Processing several measurement cycles
==============================================

```{r results='hide'}
#isDevelopMode <- TRUE
if(!exists("isDevelopMode")) library(RespChamberProc)
set.seed(0815)      # for reproducible results
```

Determine subsets of single measurment cycles
---------------------------------------------------

First, the data is loaded. Here, directly from zipped logger-output.
```{r, spar=TRUE, fig.width=12}
fName <- system.file("genData/SMANIE_Chamber1_26032015.zip", package = "RespChamberProc")
if( nzchar(fName) ){ ds <- ds0 <- readDat(unz(fName, file=unzip(fName, list=TRUE)[1,"Name"] ),tz="UTC") }
head(ds)
plot( CO2_LI840 ~ TIMESTAMP, ds, ylab="CO2 (ppm)", xlab="Time")
```

First, we correct the pressure to standard units and correct the CO2
concentrations for water vapour.
```{r}
ds$Pa <- ds0$AirPres * 100  # convert hPa to Pa
ds$CO2_dry <- corrConcDilution(ds, colConc = "CO2_LI840", colVapour = "H2O_LI840")
ds$H2O_dry <- corrConcDilution(ds, colConc = "H2O_LI840", colVapour = "H2O_LI840")
ds$VPD <- calcVPD( ds$SurTemp, ds$Pa, ds$H2O_LI840)
```

The data comprises many measurement cycles, even for the same collar. In order
to process each measurement cycle independently, we first determine parts of
the time series that are contiguous, i.e. without gaps and without change of an
index variable, here variable `collar`.

 ```{r}
dsChunk <- subsetContiguous(ds, colTime="TIMESTAMP", colIndex="Collar") 
head(dsChunk)
```

The new modified contains a new variable, `iChunk`, holding a factor that
changes with different measurment cycles.
This factor can be used to select subset of single measurement cycles. 
 ```{r , spar=TRUE}
dsChunk <- subsetContiguous(ds, colTime="TIMESTAMP", colIndex="Collar") 
head(dsChunk)
dss <- subset(dsChunk, iChunk==15)
plot( CO2_dry ~ TIMESTAMP, dss, ylab="CO2 (ppm)", xlab="time (Minute:Second)")
```

Computing the flux
---------------------
```{r}
# for demonstration use only the first 20 cycles
dsChunk20 <- subset(dsChunk, as.integer(iChunk) <= 20) 
chamberVol=0.6*0.6*0.6		# chamber was a cube of 0.6m length
surfaceArea=0.6*0.6
resL <- plyr::dlply(dsChunk20, ~iChunk, function(dss){
			cat(",",dss$iChunk[1])
			ans <- calcClosedChamberFlux(dss, colTemp="T_LI840"
					,fRegress = c(lin = regressFluxLinear, tanh = regressFluxTanh)	# linear and saturating shape
					,debugInfo=list(omitEstimateLeverage=TRUE)	# faster
					,volume=chamberVol
					,area=surfaceArea
			)		
		}
		#, .parallel=TRUE
		)
# extract the flux and its uncertainty from results list		
resStat <- plyr::ldply(resL, function(entry){ entry$stat[c("flux","sdFlux","tLag")] })
head(resStat)
```

Plot the results to dectect problems. 
```{r, spar=TRUE, fig.width=11, fig.height=6}
p1 <- plotCampaignConcSeries( dsChunk20, resL, plotsPerPage=64L)[[1]]   # first page
print(p1)
```

If argument `fileName` is provided to `plotCampaignConcSeries`. All plots are
written to a pdf with several pages.

Inspecting single fits
-------------------------
```{r}
dss <- subset(as.data.frame(dsChunk), iChunk=="8")
ans <- calcClosedChamberFlux(dss, colTemp="T_LI840"
		,fRegress = c(lin = regressFluxLinear, tanh = regressFluxTanh)	# linear and saturating shape
		,debugInfo=list(omitEstimateLeverage=TRUE)	# faster
		,volume=chamberVol
		,area=surfaceArea
)
plotResp(dss, ans, label=dss$iChunk[1])	
```
		


